digit = "0"
	| "1"
	| "2"
	| "3"
	| "4"
	| "5"
	| "6"
	| "7"
	| "8"
	| "9" .
expr = number
	| identifier
	| "(" expr ")"
	| expr "+" expr
	| expr "-" expr
	| expr "*" expr
	| expr "/" expr .
identifier = letter { letter | digit } .
letter = "a"
	| "b"
	| "c"
	| "d"
	| "e"
	| "f"
	| "g"
	| "h"
	| "i"
	| "j"
	| "k"
	| "l"
	| "m"
	| "n"
	| "o"
	| "p"
	| "q"
	| "r"
	| "s"
	| "t"
	| "u"
	| "v"
	| "w"
	| "x"
	| "y"
	| "z"
	| "A"
	| "B"
	| "C"
	| "D"
	| "E"
	| "F"
	| "G"
	| "H"
	| "I"
	| "J"
	| "K"
	| "L"
	| "M"
	| "N"
	| "O"
	| "P"
	| "Q"
	| "R"
	| "S"
	| "T"
	| "U"
	| "V"
	| "W"
	| "X"
	| "Y"
	| "Z" .
number = { digit } [ "." ] { digit } .
orderBy = orderBySingle { "," orderBySingle } .
orderBySingle = expr [ "ASC" | "DESC" ] .
selectExpr = expr [ "AS" ] [ identifier ] .
selectStmt = "SELECT" selectExpr { "," selectExpr } [ "FROM" tableRef ] [ "WHERE" whereCond ] [ "GROUP BY" identifier ] [ "ORDER BY" orderBy ] .
tableRef = identifier [ "AS" ] [ identifier ] .
whereCond = expr
	| "(" expr ")"
	| expr "AND" expr
	| expr "OR" expr .

